sudo: required 
dist: trusty 
language: generic 

cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - ROS_REPO=ros
  matrix:
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="melodic"
    - ROS_DISTRO="melodic" ROS_REPO=ros-shadow-fixed

matrix:
  allow_failures:
    - env: ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed
    - env: ROS_DISTRO="melodic" ROS_REPO=ros-shadow-fixed

install:
  - git clone --quiet --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config
script: 
  - .ci_config/travis.sh
